package com.omarshehe.tzaddress.importer

enum class ViolationKind {
    REGION_COUNT,
    BAD_DISTRICT_CODE,
    BAD_WARD_POSTCODE,
    DUPLICATE_WARD_POSTCODE,
    WARD_PREFIX_MISMATCH,
    DUPLICATE_DISTRICT_CODE,
    ANOMALY_RATIO,
    WARD_POINT_HALF,
    WARD_POINT_OUT_OF_BOUNDS,
    WARD_POINT_COVERAGE,
}
